# Validation of the Schwinger engine

According to Narozhny et al. Phys. Lett. A, 330, 1-2 (2004), the Schwinger pair
production rate per unit time per unit volume (in Gaussian units) is given by: 
$$
R = \dfrac{e^2 E_s^2}{4 \pi^2 \hbar^2 c} \epsilon \eta \coth{\left({\dfrac{\pi \eta}{\epsilon}}\right)}\exp{\left({-\dfrac{\pi}{\epsilon}}\right)}
$$
where $e$ is the elementary charge, $E_s$ is the Schwinger field, $\epsilon = \mathcal{E}/E_s$ and $\eta = \mathcal{H}/E_s$. $\mathcal{E}$ and $\mathcal{H}$ are given by:
$$
\mathcal{E} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} + \mathcal{F}} \\
\mathcal{H} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} - \mathcal{F}} \\
$$
$\mathcal{F}$ and $\mathcal{G}$ are the invariants of the electromagnetic field and are equal to:
$$
\mathcal{F} = (\mathbf{E}^2 - \mathbf{H}^2)/2 \\
\mathcal{G} = \mathbf{E} \cdot \mathbf{H} \\
$$ 
where $\mathbf{E}$ is the electric field and  $\mathbf{H}$ is the magnetic field.
The Schwinger field  $E_s$ is given by
$$
E_s = \dfrac{m_e^2 c^3}{e \hbar}
$$

### Conversion from Gaussian to SI units (see https://en.wikipedia.org/wiki/Gaussian_units)
The formula for the Schwinger field is identical
$$
E_s = \dfrac{m_e^2 c^3}{e \hbar}
$$
The expression for the two invariants becomes:
$$
\mathcal{F} = 4 \pi \epsilon_0 (\mathbf{E}^2 - c^2 \mathbf{B}^2)/2 \\
\mathcal{G} = 4 \pi \epsilon_0  c \mathbf{E} \cdot \mathbf{B} \\
$$ 
where $\epsilon_0$ is the electric permittivity and $c$ is the speed of light. However, since a factor $\sqrt{4 \pi \epsilon_0}$ should apper in the expression of  $\epsilon$ and $\eta$, we can drop the $4 \pi \epsilon_0$ in the expression of the electromagnetic invariants:
$$
\mathcal{F} = (\mathbf{E}^2 - c^2 \mathbf{B}^2)/2 \\
\mathcal{G} = c \mathbf{E} \cdot \mathbf{B} \\
$$ 
and keep  $\epsilon$ and $\eta$ defined as $\epsilon = \mathcal{E}/E_s$ and $\eta = \mathcal{H}/E_s$.
Finally, nothing changes for $\mathcal{E}$ and $\mathcal{H}$
$$
\mathcal{E} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} + \mathcal{F}} \\
\mathcal{H} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} - \mathcal{F}} \\
$$
and the formula for the rate remains identical:
$$
R = \dfrac{e^2 E_s^2}{4 \pi^2 \hbar^2 c} \epsilon \eta \coth{\left({\dfrac{\pi \eta}{\epsilon}}\right)}\exp{\left({-\dfrac{\pi}{\epsilon}}\right)}
$$

### Calculation of E_s in SI units
$E_s$ should be $\sim 1.32 \cdot 10^{18}$ V/m

In [1]:
me = 9.1093837015e-31
hbar = 1.054571817e-34
qe = 1.602176634e-19
c = 299792458

E_s = (me**2 * c**3)/(qe * hbar)
print(E_s)

1.323285474948166e+18


### Calculation of B_s in SI units (the Schwinger magnetic field)
B_s should be $\sim 4.41 \cdot 10^{9}$ T

In [2]:
B_s = E_s / c
print(B_s)

4414005221.399419


### Definition of a Schwinger pair production rate function

In [3]:
import numpy as np


def schwinger_rate(E, B):
    ff = (np.dot(E,E) - c**2 * np.dot(B,B))/2
    gg = c*np.dot(E,B)
    tt = np.sqrt(ff**2 + gg**2)
    epsi = np.sqrt(tt + ff)/E_s
    eta = np.sqrt(tt - ff)/E_s
    
    coeff = (qe**2 * E_s**2)/(4* np.pi**2 * hbar**2 * c)
    
    if epsi == 0.0:
        return 0.0
    elif eta  == 0.0 :
        return coeff * epsi*(epsi/np.pi)*np.exp(-np.pi/epsi)
    else :  
        return coeff * epsi*eta *(1./np.tanh(np.pi*eta/epsi))*np.exp(-np.pi/epsi)



### Generation of test cases

In [4]:
volume = (1.0e-27) # one cubic nanometer
dt = 1.0e-15 # one femtosecond


In [7]:
def calcandprint(E,B):
    print("***")
    print(E)
    print(B)
    volume = (1.0e-27) # one cubic nanometer
    dt = 1.0e-15 # one femtosecond
    print(schwinger_rate(E,B)*dt*volume)
    print("***")

for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*100
    B = B_s * ( np.random.rand(3) - 0.5 )*100
    calcandprint(E,B)
    
for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*10
    B = B_s * ( np.random.rand(3) - 0.5 )*10
    calcandprint(E,B)
    
for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*1
    B = B_s * ( np.random.rand(3) - 0.5 )*1
    calcandprint(E,B)
    
for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.1
    B = B_s * ( np.random.rand(3) - 0.5 )*0.1
    calcandprint(E,B)

for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.01
    B = B_s * ( np.random.rand(3) - 0.5 )*0.01
    calcandprint(E,B)
    
for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*1
    B = B_s * ( np.random.rand(3) - 0.5 )*0.0
    calcandprint(E,B)
    
for i in range(1):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.0
    B = B_s * ( np.random.rand(3) - 0.5 )*1
    calcandprint(E,B)

***
[ 1.95983374e+19  4.53196740e+19 -1.53227991e+19]
[ 1.13158072e+11 -1.85649109e+11  2.29865284e+10]
3.4139782285140736e+17
***
***
[ 4.43553420e+18 -1.48590855e+18 -4.97918545e+18]
[1.42289566e+10 1.16929194e+10 1.23891325e+10]
176465404215894.25
***
***
[ 4.54934668e+17  3.60689055e+17 -7.40223878e+16]
[ 2.15516897e+09 -1.24094282e+09  2.12944723e+08]
13260564.37996268
***
***
[-2.58846648e+16  6.36938729e+16 -4.05635306e+16]
[1.88731972e+08 1.98350731e+08 6.29021957e+07]
1.5378383291079964e-40
***
***
[-5.16985258e+15  2.73508231e+15 -6.51165687e+15]
[11147443.85927287 -9121796.02689837  4006723.35164947]
1.4667912475172131e-204
***
***
[-5.31757957e+17  2.04160390e+16  5.87459095e+16]
[ 0. -0.  0.]
7550696719.281356
***
***
[-0.  0. -0.]
[-7.48675644e+08 -1.21286777e+09 -8.53842514e+08]
0.0
***


In [9]:
E = E_s * ( np.array([1,0,0]))
B =   np.array([0,0,0])
calcandprint(E,B)
print((schwinger_rate(E,B)*dt*volume)*1.602e-10)

***
[1.32328547e+18 0.00000000e+00 0.00000000e+00]
[0 0 0]
4697522734778.629
***
752.5431421115363


In [33]:
dV = (1.e-9)**3 # total simulation volume
dt = 1.0e-15

def calculate_rate(Ex,Ey,Ez,Bx,By,Bz):
## Calculate theoretical pair production rate from EM field value

    E_squared = Ex**2 + Ey**2 + Ez**2
    H_squared = c**2*(Bx**2 + By**2 + Bz**2)

    F = (E_squared - H_squared)/2.
    G = c*(Ex*Bx + Ey*By + Ez*Bz)

    epsilon = np.sqrt(np.sqrt(F**2+G**2)+F)/E_s
    eta = np.sqrt(np.sqrt(F**2+G**2)-F)/E_s
    
    coeff = qe**2*E_s**2/4./np.pi**2/c/hbar**2
    print("DD",epsilon, eta, coeff)

    if(epsilon != 0. and eta != 0.):
        print("main", 1.0/np.tanh(np.pi*eta/epsilon)*np.exp(-np.pi/epsilon), 1.0 *(1./np.tanh(np.pi*epsilon/eta))*np.exp(-np.pi/epsilon))
        return  coeff*epsilon*eta/np.tanh(np.pi*eta/epsilon)*np.exp(-np.pi/epsilon)
    elif (epsilon == 0.):
        return 0.
    else:
        return  coeff*epsilon**2/np.pi*np.exp(-np.pi/epsilon)
    


In [34]:
E = np.array([-5.86178646e+17 ,-1.74279087e+17 , 2.92032451e+17])
B = np.array([-5.16964682e+08, -1.10073687e+09, -1.03479431e+09])
print(calculate_rate(E[0],E[1],E[2],B[0],B[1],B[2]))
print(schwinger_rate(E,B))

DD 0.3731282381929138 0.08840607593359419 3.41503467090682e+56
main 0.0003490259339372766 0.00022050157209649497
3.931814741207932e+51
DD 0.3731282381929138 0.08840607593359419 3.41503467090682e+56
main
3.931814741207932e+51


In [24]:
print(schwinger_rate(E,B)*1e-27*1e-15)

4697522734778.628


In [15]:
me**4 * c**5 / (4 * np.pi**3 * hbar**4)

1.0870392974100492e+56

In [16]:
def ff(n):
    return np.exp(-np.pi*n)/n**2

print(ff(1)+ff(2)+ff(3))

0.04368974555976263


In [17]:
0.04368974555976263*1.0870392974100492e+56*1e-27*1.6e-10*1e-15

759.879525076931