# Validation of the Schwinger engine

According to Narozhny et al. Phys. Lett. A, 330, 1-2 (2004), the Schwinger pair
production rate per unit time per unit volume (in Gaussian units) is given by: 
$$
R = \dfrac{e^2 E_s^2}{4 \pi^2 \hbar^2 c} \epsilon \eta \coth{\left({\dfrac{\pi \eta}{\epsilon}}\right)}\exp{\left({-\dfrac{\pi}{\epsilon}}\right)}
$$
where $e$ is the elementary charge, $E_s$ is the Schwinger field, $\epsilon = \mathcal{E}/E_s$ and $\eta = \mathcal{H}/E_s$. $\mathcal{E}$ and $\mathcal{H}$ are given by:
$$
\mathcal{E} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} + \mathcal{F}} \\
\mathcal{H} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} - \mathcal{F}} \\
$$
$\mathcal{F}$ and $\mathcal{G}$ are the invariants of the electromagnetic field and are equal to:
$$
\mathcal{F} = (\mathbf{E}^2 - \mathbf{H}^2)/2 \\
\mathcal{G} = \mathbf{E} \cdot \mathbf{H} \\
$$ 
where $\mathbf{E}$ is the electric field and  $\mathbf{H}$ is the magnetic field.
The Schwinger field  $E_s$ is given by
$$
E_s = \dfrac{m_e^2 c^3}{e \hbar}
$$

### Conversion from Gaussian to SI units (see https://en.wikipedia.org/wiki/Gaussian_units)
The formula for the Schwinger field is identical
$$
E_s = \dfrac{m_e^2 c^3}{e \hbar}
$$
The expression for the two invariants becomes:
$$
\mathcal{F} = 4 \pi \epsilon_0 (\mathbf{E}^2 - c^2 \mathbf{B}^2)/2 \\
\mathcal{G} = 4 \pi \epsilon_0  c \mathbf{E} \cdot \mathbf{B} \\
$$ 
where $\epsilon_0$ is the electric permittivity and $c$ is the speed of light. However, since a factor $\sqrt{4 \pi \epsilon_0}$ should apper in the expression of  $\epsilon$ and $\eta$, we can drop the $4 \pi \epsilon_0$ in the expression of the electromagnetic invariants:
$$
\mathcal{F} = (\mathbf{E}^2 - c^2 \mathbf{B}^2)/2 \\
\mathcal{G} = c \mathbf{E} \cdot \mathbf{B} \\
$$ 
and keep  $\epsilon$ and $\eta$ defined as $\epsilon = \mathcal{E}/E_s$ and $\eta = \mathcal{H}/E_s$.
Finally, nothing changes for $\mathcal{E}$ and $\mathcal{H}$
$$
\mathcal{E} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} + \mathcal{F}} \\
\mathcal{H} = \sqrt{\sqrt{\mathcal{F}^2 + \mathcal{G}^2} - \mathcal{F}} \\
$$
and the formula for the rate remains identical:
$$
R = \dfrac{e^2 E_s^2}{4 \pi^2 \hbar^2 c} \epsilon \eta \coth{\left({\dfrac{\pi \eta}{\epsilon}}\right)}\exp{\left({-\dfrac{\pi}{\epsilon}}\right)}
$$

### Calculation of E_s in SI units
$E_s$ should be $\sim 1.32 \cdot 10^{18}$ V/m

In [3]:
import scipy.constants as const
c = const.c
me = const.m_e
hbar = const.hbar
qe = const.e

E_s = (me**2 * c**3)/(qe * hbar)
print(E_s)

1.3232854658972884e+18


### Calculation of B_s in SI units (the Schwinger magnetic field)
B_s should be $\sim 4.41 \cdot 10^{9}$ T

In [4]:
B_s = E_s / c
print(B_s)

4414005191.208941


### Definition of a Schwinger pair production rate function

In [23]:
import numpy as np


def schwinger_rate(E, B):
    ff = (np.dot(E,E) - c**2 * np.dot(B,B))/2
    gg = c*np.dot(E,B)
    tt = np.sqrt(ff**2 + gg**2)
    epsi = np.sqrt(tt + ff)/E_s
    eta = np.sqrt(tt - ff)/E_s
    
    coeff = (qe**2 * E_s**2)/(4* np.pi**2 * hbar**2 * c)
        
    if epsi == 0.0:
        return 0.0
    elif eta  == 0.0 :
        return coeff * epsi*(epsi/np.pi)*np.exp(-np.pi/epsi)
    else :  
        return coeff * epsi*eta *(1./np.tanh(np.pi*epsi/eta))*np.exp(-np.pi/epsi)



### Generation of test cases

In [12]:
volume = (1.0e-27) # one cubic nanometer
dt = 1.0e-15 # one femtosecond

In [24]:
def calcandprint(E,B):
    print("***")
    print(E)
    print(B)
    print(schwinger_rate(E,B)*dt*volume)
    print("***")

for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*100
    B = B_s * ( np.random.rand(3) - 0.5 )*100
    calcandprint(E,B)
    
for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*10
    B = B_s * ( np.random.rand(3) - 0.5 )*10
    calcandprint(E,B)
    
for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*1
    B = B_s * ( np.random.rand(3) - 0.5 )*1
    calcandprint(E,B)
    
for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.1
    B = B_s * ( np.random.rand(3) - 0.5 )*0.1
    calcandprint(E,B)

for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.01
    B = B_s * ( np.random.rand(3) - 0.5 )*0.01
    calcandprint(E,B)
    
for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*1
    B = B_s * ( np.random.rand(3) - 0.5 )*0.0
    calcandprint(E,B)
    
for i in range(3):
    E = E_s * ( np.random.rand(3) - 0.5 )*0.0
    B = B_s * ( np.random.rand(3) - 0.5 )*1
    calcandprint(E,B)

***
[3.57893317e+18 5.46020302e+19 9.93627604e+18]
[-7.66560594e+10 -1.58756483e+11  3.79913127e+10]
4.633600473471703e+17
***
***
[2.63027345e+19 5.82283618e+19 5.21228166e+19]
[-1.46751168e+11 -1.13715939e+11 -2.20142017e+11]
1.2241805315872207e+18
***
***
[-5.72700255e+19  3.05690850e+19 -1.56885482e+19]
[-1.13822760e+11  1.06825949e+11  9.28231563e+10]
4.533779338036168e+17
***
***
[ 4.08924065e+18  5.09660844e+18 -3.09114980e+18]
[ 2.82723347e+09 -1.72430897e+10 -3.22323832e+09]
1924135638387076.8
***
***
[ 1.40188131e+18  2.80895435e+18 -1.30237411e+18]
[1.40480952e+10 3.88973241e+09 2.14776599e+10]
0.36323896564190056
***
***
[ 1.79831437e+17 -2.33546419e+18 -1.49073347e+18]
[ 1.91233703e+10 -5.64845738e+09  1.18296650e+10]
1.5245496593283996e-23
***
***
[ 2.84840265e+17 -2.26101913e+17  8.05255189e+16]
[-1.10232465e+09  6.27803848e+08  1.43519500e+09]
59358.92423539451
***
***
[ 1.94328962e+17  2.33617327e+16 -1.62237028e+17]
[ 4.39113097e+08  1.73396867e+09 -9.39886070e+08]
11

In [14]:
E = E_s * ( np.array([1,0,0]))
B = B_s * ( np.random.rand(3) - 0.5 )*0.0
calcandprint(E,B)

***
[1.32328547e+18 0.00000000e+00 0.00000000e+00]
[-0. -0.  0.]
<class 'numpy.float64'> 1.0
4697522743326.988
***


In [21]:
coeff = (qe**2 * E_s**2)/(4* np.pi**2 * hbar**2 * c)/np.pi
print(coeff*volume*dt*1.60e-19)

1.7392628790211182e-05
